services:
   portfolio:
      image: portfolio:dev
      container_name: portfolio
      expose:
         # Backend port exposed internally (Nginx reverse proxy will forward to this port)
         # Ensure this matches VITE_BACKEND_PORT in .env
         - "${VITE_BACKEND_PORT}"
      environment:
         NODE_ENV: ${NODE_ENV}
         VITE_API_PREFIX: ${VITE_API_PREFIX}
         VITE_BACKEND_PORT: ${VITE_BACKEND_PORT}
         VITE_BACKEND_URL: ${VITE_BACKEND_URL}
         VITE_FRONTEND_PORT: ${VITE_FRONTEND_PORT}
         VITE_GIT_COMMIT_DATE: ${VITE_GIT_COMMIT_DATE}
         VITE_RECAPTCHA_SITE_KEY: ${VITE_RECAPTCHA_SITE_KEY}
         VITE_RECAPTCHA_SECRET_KEY: ${VITE_RECAPTCHA_SECRET_KEY}
         VITE_EMAILJS_SERVICE_ID: ${VITE_EMAILJS_SERVICE_ID}
         VITE_EMAILJS_TEMPLATE_ID: ${VITE_EMAILJS_TEMPLATE_ID}
         VITE_EMAILJS_PUBLIC_KEY: ${VITE_EMAILJS_PUBLIC_KEY}
         VITE_DB_SELECT: ${VITE_DB_SELECT}
         VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
         VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
         VITE_POSTGRES_USER: ${VITE_POSTGRES_USER}
         VITE_POSTGRES_PASSWORD: ${VITE_POSTGRES_PASSWORD}
         VITE_POSTGRES_DB: ${VITE_POSTGRES_DB}
         CORS_ORIGIN: ${CORS_ORIGIN}
      volumes:
         - ./projects_assets/project_movies:/app/projects_assets/project_movies:ro
         - ./projects_assets/project_pictures:/app/projects_assets/project_pictures:ro
      restart: always
      networks: ["contado_net"]

networks:
   contado_net:
      name: contado_net
      driver: bridge
      external: true
