services:
  portfolio_webapp:
    image: react_portfolio:latest
    container_name: react_portfolio
    restart: unless-stopped
    networks: ['contado_net']
    ports:
      - "5173:5173"
    volumes:
      - ./projects_assets/project_movies:/app/src/assets/project_movies
      - ./projects_assets/project_pictures:/app/src/assets/project_pictures
    environment:
      VITE_EMAILJS_SERVICE_ID: ${VITE_EMAILJS_SERVICE_ID}
      VITE_EMAILJS_TEMPLATE_ID: ${VITE_EMAILJS_TEMPLATE_ID}
      VITE_EMAILJS_PUBLIC_KEY: ${VITE_EMAILJS_PUBLIC_KEY}
      VITE_DB_SELECT: ${VITE_DB_SELECT}
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
      VITE_POSTGRES_USER: ${VITE_POSTGRES_USER}
      VITE_POSTGRES_PASSWORD: ${VITE_POSTGRES_PASSWORD}
      VITE_POSTGRES_DB: ${VITE_POSTGRES_DB}

networks:
  contado_net:
    name: contado_net
    driver: bridge
    external: true

