version: "3.8"

services:
   app:
      build:
         context: .
         dockerfile: Dockerfile.dev
      container_name: portfolio_dev
      restart: unless-stopped
      networks: ["portfolio_net"]
      ports:
         - "5000:5000" # Server API
         - "5173:5173" # Vite dev server
      volumes:
         - .:/app
         - /app/node_modules
         - /app/client/node_modules
         - ./projects_assets/project_movies:/app/client/src/assets/project_movies
         - ./projects_assets/project_pictures:/app/client/src/assets/project_pictures
      environment:
         - NODE_ENV=development
         - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
         - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
         - VITE_GIT_COMMIT_DATE=${VITE_GIT_COMMIT_DATE}
         - VITE_RECAPTCHA_SITE_KEY=${VITE_RECAPTCHA_SITE_KEY}
         - VITE_RECAPTCHA_SECRET_KEY=${VITE_RECAPTCHA_SECRET_KEY}
         - VITE_EMAILJS_SERVICE_ID=${VITE_EMAILJS_SERVICE_ID}
         - VITE_EMAILJS_TEMPLATE_ID=${VITE_EMAILJS_TEMPLATE_ID}
         - VITE_EMAILJS_PUBLIC_KEY=${VITE_EMAILJS_PUBLIC_KEY}
         - PORT=5000

networks:
   portfolio_net:
      driver: bridge
