services:
   portfolio:
      image: portfolio:dev # Adjust image name as required
      container_name: portfolio
      ports:
         # Expose backend port to host for external access (ensure the value matches VITE_BACKEND_PORT in .env)
         - "3003:3003"
      environment:
         NODE_ENV: ${NODE_ENV}
         VITE_API_PREFIX: ${VITE_API_PREFIX}
         VITE_BACKEND_URL: ${VITE_BACKEND_URL}
         VITE_BACKEND_PORT: ${VITE_BACKEND_PORT}
         VITE_GIT_COMMIT_DATE: ${VITE_GIT_COMMIT_DATE}
         VITE_RECAPTCHA_SITE_KEY: ${VITE_RECAPTCHA_SITE_KEY}
         VITE_RECAPTCHA_SECRET_KEY: ${VITE_RECAPTCHA_SECRET_KEY}
         VITE_EMAILJS_SERVICE_ID: ${VITE_EMAILJS_SERVICE_ID}
         VITE_EMAILJS_TEMPLATE_ID: ${VITE_EMAILJS_TEMPLATE_ID}
         VITE_EMAILJS_PUBLIC_KEY: ${VITE_EMAILJS_PUBLIC_KEY}
         VITE_DB_SELECT: ${VITE_DB_SELECT}
         VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
         VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
         VITE_POSTGRES_USER: ${VITE_POSTGRES_USER}
         VITE_POSTGRES_PASSWORD: ${VITE_POSTGRES_PASSWORD}
         VITE_POSTGRES_DB: ${VITE_POSTGRES_DB}
      volumes:
         - ./projects_assets/project_movies:/app/projects_assets/project_movies:ro
         - ./projects_assets/project_pictures:/app/projects_assets/project_pictures:ro
      restart: unless-stopped
      networks: ["contado_net"]

networks:
   contado_net:
      name: contado_net
      driver: bridge
      external: true
