# Stage 1: Build the Vite app
FROM node:22-alpine AS builder
WORKDIR /app
# RUN addgroup -S nonrootgroup && adduser -S nonrootuser -G nonrootgroup \
#     && chown -R nonrootuser:nonrootgroup /app
# USER nonrootuser
COPY package*.json ./
RUN npm install 
RUN npm run pre-build
COPY . . 
RUN npm run build

# Stage 2: Serve with Node + a lightweight static server
FROM node:22-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/dist ./dist
EXPOSE 5173
CMD ["serve", "-s", "dist", "-l", "5173"]
